name: CI
on:
  push: #Act on push event on main and develop branches
    branches:
      - main
      - develop
  schedule:
    - cron: '0 2 * * MON' #At 02:00 on Monday.

jobs:
  Build:
    strategy:
      matrix:
        os: [windows, macos, ubuntu]
        jvm_version: [8, 11, 14, 15]
    runs-on: ${{ matrix.os }}-latest
    env:
      JAVA_VERSION: ${{ matrix.jvm_version }}
      OS: ${{ matrix.os }}
      TERM: dumb
    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: recursive
      # Install the JDK
      - uses: joschi/setup-jdk@v2.3.0
        with:
          java-version: ${{ matrix.jvm_version }}
      - name: Build
        shell: bash
        run: .github/scripts/build.sh
      - name: Check
        shell: bash
        run: .github/scripts/check.sh
       #Upload coverage report to Codecov by action "codecov/codecov-action@v1"
      - name: CodeCov
        uses: codecov/codecov-action@v1
  Build-Success:
    runs-on: ubuntu-latest
    needs: Build
   #If build success, create artifact and upload on GithubActions
    steps:
      - shell: bash
        run: touch ok
        #Action to upload artifact
      - uses: actions/upload-artifact@v2
        with:
          name: success
          path: ok
  CI:
    needs: Build-Success
    if: always()
    runs-on: ubuntu-latest
    #To complete CI pipeline, download artifact created previously.
    steps:
      #Action to download artifact
      - uses: actions/download-artifact@v2
        with:
          name: success
      - shell: bash
        run: '[ -f ok ]'
