name: Pull Request CI
on:
  pull_request:

jobs:
  Build-Foreign-Pull-Request:
    if: ${{ github.event.pull_request.head.repo.full_name != github.repository }}
    strategy:
      matrix:
        os: [windows, macos, ubuntu]
        jvm_version: [8, 11, 14, 15]
    runs-on: ${{ matrix.os }}-latest
    env:
      JAVA_VERSION: ${{ matrix.jvm_version }}
      OS: ${{ matrix.os }}
      TERM: dumb
    steps:
      # Checkout the repository
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: recursive
      # Install the JDK
      - uses: joschi/setup-jdk@v2.3.0
        with:
          java-version: ${{ matrix.jvm_version }}
      - name: Build
        shell: bash
        run: .github/scripts/build.sh
      - name: Check
        shell: bash
        run: .github/scripts/check.sh
        #Upload coverage report to Codecov by action "codecov/codecov-action@v1"
      - name: CodeCov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
